### ISSUE TITLE
Question about the work

### ISSUE THREAD

**Issue by vincentgc** [easezyc/deep-transfer-learning#1]
Thanks for your work. I wonder if these networks are all based on ResNet? And can you add some additional experiments without adaptation and show the results for comparison? By the way, I am glad to help you because I am also learning these algorithms of domain adaptation and try to reproduce them.

**Comment by easezyc** [comment]
Yes, these networks are all based on ResNet. I have updated the results without adaptation which comes from some papers. I have done some experiments without adaptation on ResNet. However, I can't get the similar results as the papers (my results are more high). I don't know the reason. Hence I didn't upload the ResNet code without adaptation. If you get the similar result as the papers, please tell me. Thanks for your question.
