### ISSUE TITLE
关于DAN和DDC

### ISSUE THREAD

**Issue by DRJ2016** [easezyc/deep-transfer-learning#10]
您好！在阅读论文时，我发现DAN相比于DDC，除了使用多核MMD外，还增加了多层适配。您认为多层适配是否重要？

**Comment by easezyc** [comment]
在ResNet里DAN和DDC都只加了一层，AlexNet里有多层，没具体实验过，不确定多层是否有效。

**Comment by DRJ2016** [comment]
> 在ResNet里DAN和DDC都只加了一层，AlexNet里有多层，没具体实验过，不确定多重是否有效。

感谢回复！
