### ISSUE TITLE
关于DFSAN训练过程中数据使用的问题

### ISSUE THREAD

**Issue by VoiceBeer** [easezyc/deep-transfer-learning#13]
您好前辈，非常感谢您的代码。

我有几个问题：

1. 在训练过程中，按理来说想使用全部数据的话一般是外面一层epoch循环，内里一层dataloader的循环。但是我看MFSAN里input只用了iterator的单次next()，所以每次epoch的源域和目标域的大小都只是一个batch_size吗？为什么不每次epoch将源域和目标域的所有图片都做迁移，是考虑到时间成本之类的问题吗？或者是采样的技巧吗？

2. 跟上个问题性质差不多，举个例子在MFSAN2中，按照您的代码的话，在第一个epoch中，是source1的第一个batch跟target的第一个batch去计算，然后source2的第一个batch是跟target的第二个batch去计算了。target不是同一个batch的话，会不会有些影响？

非常感谢您的回答，祝前辈中好多顶会 :>

**Comment by easezyc** [comment]
问题1：这只是写法问题，iterator的next()实际上和你说的整个循环(enumerate)是一样的效果。区别在于如果是整个循环，要么对src_data_loader循环要么对tgt_data_loader，然后到达一个loader结束，该epoch结束，那么大的那个loader其实是没迭代完的，下一个epoch又重新定义data_loader。而我这种写法保证了data_loader迭代完了才定义下一个data_loader。有一种同步和异步的感觉。另外如果按照epoch大小来写，比如Office31数据集，A->W可能20epoch就收敛了，而D->A可能要800epoch，后面我就统一改成了现在iteration的写法。
问题2：个人认为target是否为同一个batch影响不大，你可以去试试。

**Comment by easezyc** [comment]
推荐参考MFSAN循环的写法(按照iteration)，DSAN实际上也是按照epoch来的。

**Comment by VoiceBeer** [comment]
明白了，非常感谢前辈！

**Comment by VoiceBeer** [comment]
对了前辈，还是有个问题

我是按照MFSAN写法写的，现在的理解是这样：虽然每次epoch使用到的图像只有batch_size:32，但是epoch大了也能达到一样的效果且能增加随机性。但是考虑到一个问题，MFSAN中batch_size有32，循环了15000次，我看了target的数据集也没有32*15000张图，按理说到后面应该next()后会报错吧？我没看到哪里有处理这个问题的地方，请问您是怎么做的？

**Comment by easezyc** [comment]
try:
            target_data, __ = target_iter.next()
        except Exception as err:
            target_iter = iter(target_train_loader)
            target_data, __ = target_iter.next()
所以try except语法，报错就重新定义iter

**Comment by VoiceBeer** [comment]
噢噢原来如此 非常感谢！
