### ISSUE TITLE
DSAN

### ISSUE THREAD

**Issue by Sir-Death** [easezyc/deep-transfer-learning#14]
为什么我运行DSAN时达不到论文里的准确率

**Comment by easezyc** [comment]
注意参数设置，任务a->d  a->w  Config.py中param设为0.5，别的任务0.3，  d->a  w->a 设为0.3，epoch设为800。

**Comment by Sir-Death** [comment]
office-home和image-clef中的param也是0,3吗，为什么我运行office-home时，准确率到后来会下降

**Comment by easezyc** [comment]
officehome好像是0.5（0.3  0.5  1试试吧，忘记具体了），imageclef好像也是0.5，officehome的有的任务是会出现运行久了正确率下降的情况，正常情况。文中准确率无问题，officehome imageclef上没有进行任何参数调整。

**Comment by Sir-Death** [comment]
这个正确率下降是偶然情况吗，机器差，实验运行的很慢，没有多次跑

**Comment by easezyc** [comment]
应该是在有几个任务上一定会下降的，主要原因可能是因为用到假标签，假标签用错了，就可能导致这种情况发生。

**Comment by Sir-Death** [comment]
不好意思，我对实验方面不是很了解，所以对于运行久了正确率下降的情况，我是可以取前面的结果，而不用最后的epoch的结果吗

**Comment by easezyc** [comment]
嗯，结果记录的是最好的那一轮

**Comment by Sir-Death** [comment]
好的，非常感谢您的耐心解答
