### ISSUE TITLE
关于迁移中测试集和训练集的问题

### ISSUE THREAD

**Issue by VoiceBeer** [easezyc/deep-transfer-learning#15]
前辈您好！

再一次来提问，在训练模型过程中要避免测试集和训练集有交集。但是迁移学习中的话也要避免吗？毕竟迁移的训练过程中，目标域是作为无标签的数据来进行迁移的，迁移完后再在目标域上测试，我不知道这样算不算是模型得到了测试集的信息。我之前看您的代码data_loader中是使用了两种transform，但是也很难保证完全没有交集吧？

最近在写别的课题的时候又碰到了这个问题所以想来请教一下。非常感谢！

**Comment by easezyc** [comment]
这没问题，有transductive和inductive的区别，参考https://www.zhihu.com/question/68275921

**Comment by VoiceBeer** [comment]
非常感谢！
