### ISSUE TITLE
TSNE visualization

### ISSUE THREAD

**Issue by ashiqimran** [easezyc/deep-transfer-learning#16]
Hello,
I was going through the paper DSAN and codebase. I was wondering could you make the TSNE visualization available as well. It will be helpful for me. I will cite your paper

**Comment by easezyc** [comment]
Give me your email

**Comment by ngaruniki** [comment]
Hi, i am trying to implement Active Learning and Transfer Learning. Now i have completed AL part, could you advise how to proceed? i can share my kaggle code

**Comment by ashiqimran** [comment]
Hi @easezyc , my email is ashiq.imran@mavs.uta.edu
THanks for your response.

**Comment by easezyc** [comment]
@ngaruniki I am not sure how to implement Active learning. You can refer to "Collaborative and Adversarial Network for Unsupervised domain adaptation" which utilizes incremental learning.

**Comment by Sir-Death** [comment]
I also want the t-sne visualization,could you send me one,my email is zhq1412@qq.com,thank you

**Comment by arashi-1224** [comment]
Hi, I also want the t-sne visualization code, could you please send me one? my email is arashi_1224@qq.com, thank you!

**Comment by davidpqc1231** [comment]
Hi, can you send a copy of the t-sne visualization code? My email is qupeng@iu.edu, thanks so much!
