### ISSUE TITLE
请问作者有没有中文版的论文

### ISSUE THREAD

**Issue by Galaxy-Ding** [easezyc/deep-transfer-learning#19]
你好，我下载的英文论文看的有点费力，可能是专业术语太多了把。
谢谢，dlhes@qq.com

**Comment by easezyc** [comment]
没有中文版，直接写的英文。

**Comment by Galaxy-Ding** [comment]
感谢回复，我在王博士那里下载了迁移学习的入门手册，我看看亭不错，看了之后估计看您论文会有很大帮助




------------------&nbsp;Original&nbsp;------------------

**Comment by easezyc** [comment]
嗯嗯，这些方法的思想是互通的，可以从那本书开始入门
