### ISSUE TITLE
question about the result of the DAN

### ISSUE THREAD

**Issue by yuzehui1996** [easezyc/deep-transfer-learning#2]
I have run the codes in the DAN but the result shows that acc is always 100% no matter what is the source and what is the target. Do you know the reason? Or did I made any mistakes? I run the codes according to your readme. Thanks a lot!

**Comment by easezyc** [comment]
Yeah, the max acc is always 100% in task webcam to dslr, and the max acc in the task with most methods such as DDC is also 100%. Hence, here I record the acc of the last epoch.
