### ISSUE TITLE
Question about the dataset and ImageFolder in MFSAN

### ISSUE THREAD

**Issue by davidpqc1231** [easezyc/deep-transfer-learning#20]
大佬您好，想请问一下MFSAN中关于dataset和ImageFolder的问题。

1. 我一开始下载您提供的office31，目录的结构是dataset/domain_name/images/class_name/具体图像，直接运行发现准确率100%。想问一下这里默认的结构是不是dataset/domain_name/class_name/具体图像？
2. 我按照dataset/domain_name/class_name/具体图像设置，但是发现target out of bounds。查看dataloader发现虽然生成了31个label，但是是从1到31而非0-30。想请教把class_number设成32是否可行？以及有没有办法把label弄到0-30？

**Comment by easezyc** [comment]
这个问题之前有人遇到过，你参考https://github.com/easezyc/deep-transfer-learning/issues/4
按理说你如果把类别改成32可能会不太对，softmax的分母就是32个输出之和，可能会有问题

**Comment by davidpqc1231** [comment]
谢谢！
