### ISSUE TITLE
What is the license of your code?

### ISSUE THREAD

**Issue by SunHaozhe** [easezyc/deep-transfer-learning#22]
What is the license of your code? Can we copy or modify your code for academic research?

Best regards,

**Comment by easezyc** [comment]
I did not choose any license. This code is public to facilitate academic research, so everyone can use it to do academic research。

**Comment by SunHaozhe** [comment]
May you want to add a LICENSE to your project please, if that does not bother you? 

Adding a license can protect both the code authors and users. It protects the code authors in terms of liability and warranty. It protects the users so that they do not need to worry about license issues, which should also promote the popularity of this code. If you are interested, here are some of the good references:

* https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository
* https://choosealicense.com/

**Comment by easezyc** [comment]
Done
