### ISSUE TITLE
Question about the evaluation or the test with MFSAN

### ISSUE THREAD

**Issue by davidpqc1231** [easezyc/deep-transfer-learning#23]
大佬您好，抱歉打扰了。我试了office-31的DW2A，发现结果很好，但是在AD2W跟AW2D上感觉达不到paper的结果。另外office-home的ACP2R也是。我想是不是有什么test上面的tricks？因为像AD2W，D的部分结果是明显好于A的部分，按照代码里头算平均，结果就会弱一些。请问是不是要做一些加权之类的？

**Comment by easezyc** [comment]
这个没啥tricks，我直接把我跑实验的代码上传的。有微小差距是很正常的，毕竟我也只跑了三次取的平均。这个加权平均，我论文里的结果都是用的0.5的权重，其实如果有这样的先验知识，融入一些人为先验来设置权重应该是会更好的，比如你说的AD2W，D的头权重设置大一些，理论上应该会更好。

**Comment by davidpqc1231** [comment]
好的，谢谢你！
