### ISSUE TITLE
Reproducing t-SNE results

### ISSUE THREAD

**Issue by daddyke** [easezyc/deep-transfer-learning#24]
Hi,

First of all, thanks for the great work! 

For DSAN, I am wondering if you can also release the source code of reproducing the T-SNE results. I tried the T-SNE pytorch version but the generated result is different from the one reported in the paper. 

UPDATE: I saw there is a closed post that asking for t-SNE implementation and you want them to provide the email address. Would you please also send me a copy of code? My email address is: yunke8@vt.edu

Thanks for your valuable time and I am looking forward to hearing from you soon!

**Comment by easezyc** [comment]
I cannot find the latest version of the t-sne code. I have sent you an early version.

**Comment by daddyke** [comment]
Thank you so much!
