### ISSUE TITLE
关于SRC和TAR类别无法匹配的训练策略

### ISSUE THREAD

**Issue by tongyuhome** [easezyc/deep-transfer-learning#25]
您好，感谢您的工作。
想请教一下目前使用的数据集源类别和目标类别是一致对应的，如果两者类别无法对应的情况（比如SRC中有ABC三类，而TAR中有ABD三类），有什么好的训练策略可以改善效果吗？

**Comment by easezyc** [comment]
你可以去了解下partial transfer, transfer learning in open set, universal transfer。这些问题关注源领域和目标领域类别不完全一致的情况。

**Comment by tongyuhome** [comment]
> 你可以去了解下partial transfer, transfer learning in open set, universal transfer。这些问题关注源领域和目标领域类别不完全一致的情况。

非常感谢您的回复！
