### ISSUE TITLE
MRAN-Running error -AttributeError: 'SGD' object has no attribute 'param_group'

### ISSUE THREAD

**Issue by zhen1202** [easezyc/deep-transfer-learning#26]
Traceback (most recent call last):
  File "MRAN.py", line 131, in <module>
    optimizer.param_group[0]['lr'] = args.lr[0] / math.pow((1 + 10 * (epoch - 1) / args.epochs), 0.75)
AttributeError: 'SGD' object has no attribute 'param_group'

**Comment by easezyc** [comment]
I have corrected the codes, and there is no error now.

**Comment by zhen1202** [comment]
Thank you
