### ISSUE TITLE
when will the MRAN code be uploaded

### ISSUE THREAD

**Issue by zy199676** [easezyc/deep-transfer-learning#28]

**Comment by easezyc** [comment]
The MRAN code was released three years ago.
https://github.com/easezyc/deep-transfer-learning/tree/master/UDA/pytorch1.0/MRAN

**Comment by zy199676** [comment]
> The MRAN code was released three years ago. https://github.com/easezyc/deep-transfer-learning/tree/master/UDA/pytorch1.0/MRAN

thank you
