### ISSUE TITLE
Problem about the t-SNE

### ISSUE THREAD

**Issue by DanJun6737** [easezyc/deep-transfer-learning#29]
您好，非常棒的工作，谢谢您的开源分享！
我在尝试复现您的工作DSAN，但是t-SNE出来的效果不太理想。
请问在A-->W这个任务上，您t-SNE可视化时选取的源域和目标域的样本分别是多少呢？
我两个域都选取的是480个样本，但出来的图效果不好。
如果可以的话能否分享一下t-SNE的代码呢？ email: 673781472@qq.com

期待您的回复！谢谢！

**Comment by easezyc** [comment]
A->W用全样本，特征用fc后256维的

**Comment by DanJun6737** [comment]
收到，谢谢。

**Comment by salted-fish-can** [comment]
> 

您好！请问能分享一下您的t-SNE的代码吗？我找了好多都没有这方面的代码，谢谢，邮箱1946552068@qq.com
