### ISSUE TITLE
A supplement to dataset of DAN

### ISSUE THREAD

**Issue by MiaoHaoSunny** [easezyc/deep-transfer-learning#4]
if you are in a situation where soft-loss is equal to 0 and accuracy is 100%, you probably meet the same problem as me. You might need to check your dataset and ensure that sub-classes are under the category folder such as bike and back_pack instead of images. The correct data set layout is shown in the figure. I hope this works and can help you.
![示例图片](https://user-images.githubusercontent.com/37861076/55678317-207be600-592a-11e9-8864-3924ca3b1541.png)

**Comment by easezyc** [comment]
Thanks for your contribution.

**Comment by 459548764** [comment]
Very useful !!!

**Comment by slowlyswimming** [comment]
The accuracy goes under 100% now. Great tips.

**Comment by VoiceBeer** [comment]
Thx for the tip, I think this issue should be added into the `README.md`

**Comment by PrinceSJ** [comment]
Helpful supplement! Thanks 😊

**Comment by heeler-deer** [comment]
helpful, thanks
