### ISSUE TITLE
How to understand the MMD Loss?

### ISSUE THREAD

**Issue by taylover-pei** [easezyc/deep-transfer-learning#5]
You have done a great job, but I have a question about the MMD Loss.

You use the guassian kernel for computing, what are the **kernel_mul** and **kernel_num** mean in your code?
![image](https://user-images.githubusercontent.com/27360803/64255557-30890780-cf54-11e9-8818-43a6c41817f6.png)
Thank you very much.

**Comment by easezyc** [comment]
Actually, the implementation is MKMMD as shown in DAN and the kernel_num means the number of guassian kernel. I consider the kernel_mul is a parameter to control the bandwidth. By 'bandwidth /= kernel_mul ** (kernel_num // 2)', we could get the min_bandwidth. Then, you need compute 5(kernel_num) bandwidth for each kernel. You get bandwidth_list = [min_bandwidth, min_bandwidth * kernel_mul, min_bandwidth * kernel_mul^2 ..... ]

**Comment by taylover-pei** [comment]
In your MRAN implementation, I think just one MMD Loss is used, that means just one kernel is OK, why you use the 5 kernels?

**Comment by easezyc** [comment]
It is ok to use one kernel, but MKMMD could achieve better performance as DAN shown.



---Original---
